# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectRoughDesign' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectRoughDesign
  pod 'SnapKit'
  target 'ProjectRoughDesignTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectRoughDesignUITests' do
    # Pods for testing
  end

end
